### ISSUE TITLE
代码里面缺函数“solve_pose_by_ransac_kabsch”，“MultiStageLrUpdaterHook”

### ISSUE THREAD

**Issue by capf-2011** [YangHai-1218/PseudoFlow#1]
您好，您的工作很棒，我想复现您的工作，但是发现代码缺部分函数，可能是您未上传完全，希望得到您的解答，谢谢，再次感谢您的工作！
![图片](https://github.com/YangHai-1218/PseudoFlow/assets/49231801/d876997f-f89e-4a5d-a267-c954691c1f51)
![图片](https://github.com/YangHai-1218/PseudoFlow/assets/49231801/7e619fc9-9573-4e9f-ac5c-d19cf76fda51)

**Comment by YangHai-1218** [comment]
这部分代码不需要，感谢关注

**Comment by Howard-Lee-666** [comment]
不好意思，我没明白，您在base_flow_refiner.py和wdr_pose.py不都调用了solve_pose_by_ransac_kabsch吗？

**Comment by Chengyang852** [comment]
请问您复现成功了吗，想请教下，配置文件中的mesh_dir=dataset_root + '/models_1024'，这个目录是哪里来的，是数据集中自带的吗，使用数据集中的会报错：ValueError: Meshes does not have textures
